//! The averaged magnitude spectrum of one logged channel (LTHL-20).
//!
//! ===========================================================================
//! THIS IS A SECOND IMPLEMENTATION OF A LAW, AND THAT IS NORMALLY THE BUG
//! ===========================================================================
//!
//! `tools/resonance_analysis.py` already computes this. It is validated to 0.6% on synthetic
//! modes, it is what the whole LTHL-18 corpus was analysed with, and `logs.md` names "a second
//! spelling of one law" as exactly the failure the recorder derives nothing in order to avoid.
//!
//! It is written here anyway for one reason: Godot has no numpy, and a shipped product that tells
//! a builder to go and run a Python script is not a product feature. The FFT has to be in the
//! binary.
//!
//! That is only acceptable because something forces the two to agree. `tests/test_spectrum.gd`
//! runs one recorded log through this code and compares it against a spectrum produced by
//! `resonance_analysis.spectrogram` itself, regenerated by `tools/spectrum_oracle.py`. The
//! precedent is `tests/rust_crosscheck_tier2.gd`, which pins the Rust fitting functions against a
//! verbatim transcription of the GDScript they replaced.
//!
//! ===========================================================================
//! EVERY CONSTANT AND EVERY CHOICE BELOW IS PYTHON'S, DELIBERATELY
//! ===========================================================================
//!
//! Windowing and detrending are CHOICES, not defaults, and two implementations that made them
//! independently would compare two different questions and agree about neither.
//! `impact_analysis.py`'s finding — that a Hann window destroys a ringdown — is the standing
//! reminder in this project that the window is part of the measurement.
//!
//! So: the frame length, the overlap, the symmetric Hann taper, and the per-frame mean removal
//! are transcribed from `spectrogram()` rather than chosen. `np.hanning` is SYMMETRIC
//! (denominator `n - 1`), not the periodic Hann most DSP libraries default to, and the difference
//! is one sample of phase — small, real, and enough to make a crosscheck fail for a reason nobody
//! would find quickly.

use rustfft::num_complex::Complex;
use rustfft::FftPlanner;

/// Analysis frame length in seconds. `resonance_analysis.FRAME_SECONDS`. Pre-registered: a fixed
/// duration rather than a fixed sample count, so a 1 kHz Lothal log and an 8 kHz Betaflight log
/// are asked the same question at the same frequency resolution.
pub const FRAME_SECONDS: f64 = 1.024;

/// `resonance_analysis.OVERLAP_FRACTION`.
pub const OVERLAP_FRACTION: f64 = 0.75;

/// What one run of the transform produced, or why it produced nothing.
pub struct Spectrum {
    pub mags: Vec<f64>,
    pub frame_len: usize,
    pub hop: usize,
    pub frames: usize,
    /// Frames dropped for containing a non-finite sample. `LogReader` writes NaN into cells that
    /// will not parse, so a corrupt row must not turn the whole spectrum into NaN.
    pub skipped: usize,
}

/// Frame layout for a signal of `len` samples at `fs`. Returned even when it does not fit, so the
/// caller can say how long a log would have to be.
pub fn frame_layout(len: usize, fs: f64) -> (usize, usize, usize) {
    let frame_len = (FRAME_SECONDS * fs).round() as usize;
    let hop = (((frame_len as f64) * (1.0 - OVERLAP_FRACTION)).round() as usize).max(1);
    let frames = if frame_len == 0 || len < frame_len {
        0
    } else {
        (len - frame_len) / hop + 1
    };
    (frame_len, hop, frames)
}

/// `np.hanning(n)` — the SYMMETRIC Hann. See the module header: this is not the periodic one.
fn hann(n: usize) -> Vec<f64> {
    if n <= 1 {
        return vec![1.0; n];
    }
    let denominator = (n - 1) as f64;
    (0..n)
        .map(|i| 0.5 - 0.5 * (std::f64::consts::TAU * (i as f64) / denominator).cos())
        .collect()
}

/// The mean over frames of the Hann-windowed magnitude spectrum, one bin per `fs / frame_len`.
///
/// This is `spectrogram()` followed by `frames.mean(axis=0)`. The averaging is the part that is
/// NOT in Python — Python keeps the frames because it order-tracks through them, and Studio draws
/// a single curve. Averaging a set of magnitude spectra is not a choice with a hidden alternative
/// the way windowing is; it is what "the spectrum of this flight" means once there is more than
/// one frame of it.
///
/// Returns `Err` with a sentence rather than panicking. This is reached from a `#[func]` in a
/// crate built with `panic = "abort"`.
pub fn averaged(samples: &[f64], fs: f64) -> Result<Spectrum, String> {
    if !fs.is_finite() || fs <= 0.0 {
        return Err(format!("sample rate {fs} is not a positive number"));
    }

    let (frame_len, hop, frames) = frame_layout(samples.len(), fs);
    if frames == 0 {
        return Err(format!(
            "the trace is {:.2} s, shorter than one {FRAME_SECONDS} s analysis frame",
            samples.len() as f64 / fs
        ));
    }

    let window = hann(frame_len);
    let bins = frame_len / 2 + 1;
    let mut total = vec![0.0f64; bins];
    let mut counted = 0usize;
    let mut skipped = 0usize;

    let mut planner = FftPlanner::<f64>::new();
    let fft = planner.plan_fft_forward(frame_len);
    let mut buffer: Vec<Complex<f64>> = vec![Complex { re: 0.0, im: 0.0 }; frame_len];

    for frame in 0..frames {
        let start = frame * hop;
        let slice = match samples.get(start..start + frame_len) {
            Some(s) => s,
            None => break,
        };

        // A frame with a NaN in it is DROPPED, not repaired. Interpolating across an unparseable
        // cell would invent a sample the flight never produced, at whatever frequency the
        // interpolation happened to imply, and then average it into every bin.
        if slice.iter().any(|v| !v.is_finite()) {
            skipped += 1;
            continue;
        }

        // Per-frame mean removal, Python's `x[s:s+n] - x[s:s+n].mean()`. Without it bin 0 carries
        // the whole DC level of the frame and its Hann sidelobes leak up into the first few bins,
        // which is where a slow log's interesting structure is.
        let mean = slice.iter().sum::<f64>() / (frame_len as f64);
        for (i, value) in slice.iter().enumerate() {
            let tapered = (value - mean) * window.get(i).copied().unwrap_or(0.0);
            if let Some(cell) = buffer.get_mut(i) {
                *cell = Complex { re: tapered, im: 0.0 };
            }
        }

        fft.process(&mut buffer);

        // Only the first n/2+1 bins: the input is real, so the rest is the mirror image. This is
        // what makes it an rfft.
        for (bin, slot) in total.iter_mut().enumerate() {
            if let Some(c) = buffer.get(bin) {
                *slot += c.norm();
            }
        }
        counted += 1;
    }

    if counted == 0 {
        return Err(format!(
            "all {frames} analysis frames contain unreadable samples"
        ));
    }

    let scale = 1.0 / (counted as f64);
    for slot in total.iter_mut() {
        *slot *= scale;
    }

    Ok(Spectrum {
        mags: total,
        frame_len,
        hop,
        frames: counted,
        skipped,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `np.hanning(5)` is [0, 0.5, 1, 0.5, 0] — the endpoints are zero, which is what makes it
    /// symmetric rather than periodic. A periodic Hann of length 5 has no zero at the end.
    #[test]
    fn hann_is_symmetric_not_periodic() {
        let w = hann(5);
        assert!((w[0] - 0.0).abs() < 1e-12);
        assert!((w[1] - 0.5).abs() < 1e-12);
        assert!((w[2] - 1.0).abs() < 1e-12);
        assert!((w[4] - 0.0).abs() < 1e-12);
    }

    /// A pure tone lands in the bin nearest its frequency. 200 Hz at 1 kHz with a 1024-sample
    /// frame is bin 205 (200 / (1000/1024) = 204.8).
    #[test]
    fn a_tone_lands_in_its_bin() {
        let fs = 1000.0;
        let samples: Vec<f64> = (0..4000)
            .map(|i| (std::f64::consts::TAU * 200.0 * (i as f64) / fs).sin())
            .collect();
        let s = averaged(&samples, fs).expect("4 s of tone is longer than one frame");
        let peak = s
            .mags
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.total_cmp(b.1))
            .map(|(i, _)| i)
            .unwrap_or(0);
        let bin_hz = fs / (s.frame_len as f64);
        assert!(((peak as f64) * bin_hz - 200.0).abs() < bin_hz);
    }

    /// A frame carrying a NaN is dropped and the rest still produce a spectrum.
    #[test]
    fn a_nan_drops_only_its_own_frame() {
        let fs = 1000.0;
        let mut samples: Vec<f64> = (0..4000)
            .map(|i| (std::f64::consts::TAU * 200.0 * (i as f64) / fs).sin())
            .collect();
        samples[0] = f64::NAN;
        let s = averaged(&samples, fs).expect("later frames are clean");
        assert!(s.skipped > 0);
        assert!(s.frames > 0);
        assert!(s.mags.iter().all(|m| m.is_finite()));
    }

    #[test]
    fn a_short_trace_is_a_reason_not_a_panic() {
        assert!(averaged(&[1.0, 2.0, 3.0], 1000.0).is_err());
        assert!(averaged(&[], 1000.0).is_err());
        assert!(averaged(&[1.0; 4000], 0.0).is_err());
    }
}
