class_name TestFingerprintSurvival
extends RefCounted
## F9: the terrain and wind terms in the lap fingerprint — and the proof that adding them orphans
## no best lap that already exists.
##
## ---------------------------------------------------------------------------
## WHY THIS SUITE IS BUILT AROUND A FIXTURE AND NOT AROUND AN ASSERTION
## ---------------------------------------------------------------------------
##
## `GateCourse.fingerprint()` is the key a best lap is filed under. Appending a term to it that
## was not there before does not corrupt anything and does not raise anything — it silently files
## every future lap under a new key, and every record a builder has ever set becomes unreachable.
## There is no error to catch. The only thing that can catch it is a best-lap file written BEFORE
## the terms existed, read back through the code that has them, and found.
##
## So `tests/fixtures/best_laps_pre_field.json` is written by the shipped pre-F1 `gate_course.gd`
## — `git show 3a64a7b:src/course/gate_course.gd`, compiled at runtime by
## `tools/f9_make_fixture.gd`, which is kept in the repo as this fixture's provenance — and by
## `LapTimer.save_best()`, which is byte-identical at HEAD to what it was at 3a64a7b. A fixture
## generated by the code it is meant to guard is a test that cannot fail, which is exactly the
## defect this project cares most about.
##
## The two hashes below are therefore GOLDEN VALUES TAKEN FROM OUTSIDE THE IMPLEMENTATION. One of
## them, `f106fd00d916b853`, was already pinned independently in `tests/test_air_density.gd` before
## any of the field room existed — and the pre-F1 harness reproducing it is the cross-check that
## the harness really is the old code.
##
## ---------------------------------------------------------------------------
## THE PAIR THAT MAKES §1 MEAN SOMETHING
## ---------------------------------------------------------------------------
##
## "The record is still found" passes trivially if the hash ignores everything. So §1 also asserts
## that a lap set on the flat, calm default circuit is NOT returned once the wind is switched on —
## a lap flown downwind is not a best on a still day. Under the mutation that appends both terms
## unconditionally the first check goes red and the second stays green; under a mutation that
## removes the terms entirely the first stays green and the second goes red. Neither alone is
## evidence.

## The default circuit, flat and calm: the hash the pre-F1 code produced for it, and the same value
## `TestAirDensity.PRE_AIR_DEFAULT_FINGERPRINT` has pinned since before terrain or wind existed.
const PRE_FIELD_DEFAULT_FINGERPRINT := "f106fd00d916b853"
## The same rings with a v1 `air` block on them (3500 m, 20 °C), as the pre-F1 code hashed them.
## Its `rho=` term is what makes the migration check below worth running: if F1's migration moved
## the elevation and the temperature anywhere other than where `AirDensity.compose()` looks, this
## number stops matching.
const PRE_FIELD_LEH_FINGERPRINT := "33c4aaf059e9d87e"

## The two times in the fixture, as typed into `tools/f9_make_fixture.gd`. Nothing computes them.
const DEFAULT_CIRCUIT_BEST_S := 41.37
const LEH_CIRCUIT_BEST_S := 48.02

const BEST_LAPS_FIXTURE := "res://tests/fixtures/best_laps_pre_field.json"
const COURSES_V1_FIXTURE := "res://tests/fixtures/courses_pre_field_v1.json"

## Scratch paths. NOT `CourseLibrary.SAVE_PATH` / `SiteLibrary.SAVE_PATH` and never
## `LapTimer.SAVE_PATH` — the migration REWRITES the courses file it is handed, and a suite that
## pointed it at the real one would migrate a builder's own library as a side effect of running
## the tests.
const SCRATCH_BEST_LAPS := "user://test_f9_best_laps.json"
const SCRATCH_COURSES := "user://test_f9_courses.json"
const SCRATCH_SITES := "user://test_f9_sites.json"

const SAME_S := 1.0e-6

## A wind nobody could call calm, pointing somewhere nobody could call north.
const TEST_WIND_MPS := 6.0
const TEST_WIND_FROM_DEG := 135.0
## A gust amplitude with no steady wind under it — the set that `is_calm()` calls weather and the
## fingerprint must not.
const TEST_GUSTINESS_MPS := 6.0


static func run() -> Array:
	var results: Array = []
	var sections := {
		"pre-field records survive": _pre_field_records_survive(),
		"the pinned hash is unmoved": _the_pinned_hash_is_unmoved(),
		"migration keeps the hash": _migration_keeps_the_hash(),
		"terrain reaches the hash": _terrain_reaches_the_hash(),
		"an unreadable shape is flat": _an_unreadable_shape_is_flat(),
		"wind reaches the hash": _wind_reaches_the_hash(),
		"gustiness does not": _gustiness_does_not(),
		"the rho term still lands": _the_rho_term_still_lands(),
		"two predicates gate the appends": _two_predicates_gate_the_appends(),
	}
	_clean_scratch()
	# A runtime error partway through a section aborts only that section and its append never runs,
	# so the suite would pass with its best checks silently deleted. Asserting each section produced
	# something is what makes the count trustworthy.
	for label in sections:
		var section: Array = sections[label]
		results.append(TestResult.new(
			"section \"%s\" produced results" % label, not section.is_empty(),
			"%d checks" % section.size()))
		results.append_array(section)
	return results


# ---------------------------------------------------------------------------
# 1. The fixture: a best lap set before the field room existed is still found
# ---------------------------------------------------------------------------

static func _pre_field_records_survive() -> Array:
	var out: Array = []

	# THE GUARD BEFORE THE COMPARISON. Everything below compares a stored time against a typed one,
	# and a fixture that failed to load hands every one of those comparisons a 0.0 on both sides
	# forever. Two absent records compare equal under every mutation, so the file's own contents
	# are asserted first, by the key and the value, before anything reads through LapTimer.
	var raw := JsonStore.read_document(BEST_LAPS_FIXTURE)
	var stored: Variant = raw.get("best_laps", {})
	var table: Dictionary = stored if stored is Dictionary else {}
	out.append(TestResult.new(
		"the pre-field fixture carries exactly the two records it was written with",
		table.size() == 2 and table.has(PRE_FIELD_DEFAULT_FINGERPRINT)
			and table.has(PRE_FIELD_LEH_FINGERPRINT),
		"%s" % [table.keys()]))

	var migrated := _migrate_the_v1_fixture()
	var library := CourseLibrary.load_from(SCRATCH_COURSES)
	var default_circuit := library.course("default_circuit")
	var leh := library.course("leh_circuit")
	out.append(TestResult.new(
		"both v1 fixture courses came back through the migration",
		default_circuit != null and leh != null,
		"%s" % [library.ids()]))
	if default_circuit == null or leh == null:
		return out

	# Copied rather than read in place, because LapTimer opens its save path for writing the moment
	# anything records a lap, and the fixture is a committed file.
	_copy(BEST_LAPS_FIXTURE, SCRATCH_BEST_LAPS)

	for pair in [["default_circuit", default_circuit, DEFAULT_CIRCUIT_BEST_S],
			["leh_circuit", leh, LEH_CIRCUIT_BEST_S]]:
		var label: String = pair[0]
		var course: GateCourse = pair[1]
		var expected_s: float = pair[2]
		var site: Site = migrated.site(course.site_id)
		out.append(TestResult.new(
			"\"%s\" has the site the migration made for it" % label, site != null,
			"site_id %s" % course.site_id))
		if site == null:
			continue
		var conditions := _conditions_for(site)
		var key := course.fingerprint(AirDensity.compose(site, conditions), site, conditions)
		var timer := LapTimer.new(key, SCRATCH_BEST_LAPS)
		out.append(TestResult.new(
			"the best lap set on \"%s\" before the field room existed is still found" % label,
			absf(timer.best_lap_s - expected_s) < SAME_S,
			"%.2f s under %s (wanted %.2f s)" % [timer.best_lap_s, key, expected_s]))

	# THE OTHER HALF OF THE PAIR. If the terms did not reach the hash at all, every check above
	# would still pass — so a record set on the still day must NOT be returned on a windy one.
	var here: Site = migrated.site(default_circuit.site_id)
	if here != null:
		var windy := _windy()
		var windy_key := default_circuit.fingerprint(
			AirDensity.compose(here, windy), here, windy)
		var windy_timer := LapTimer.new(windy_key, SCRATCH_BEST_LAPS)
		out.append(TestResult.new(
			"the same lap is NOT returned once the wind is switched on",
			windy_timer.best_lap_s == 0.0 and windy_key != PRE_FIELD_DEFAULT_FINGERPRINT,
			"%.2f s under %s" % [windy_timer.best_lap_s, windy_key]))
	return out


# ---------------------------------------------------------------------------
# 2. The pinned hash, with the arguments passed and with none passed at all
# ---------------------------------------------------------------------------

static func _the_pinned_hash_is_unmoved() -> Array:
	var out: Array = []
	var course := GateCourse.new(GateCourse.build_gates())

	# The flat-at-zero site and the calm conditions a fresh install flies in, PASSED IN — the path
	# every caller in the field room takes.
	var here := Site.new()
	var calm := Conditions.standard()
	out.append(TestResult.new(
		"a flat site and calm conditions leave the default circuit's hash where it was",
		course.fingerprint(AirDensity.compose(here, calm), here, calm)
			== PRE_FIELD_DEFAULT_FINGERPRINT,
		"%s (was %s)" % [course.fingerprint(AirDensity.compose(here, calm), here, calm),
			PRE_FIELD_DEFAULT_FINGERPRINT]))

	# And the default-argument path, which is what every caller OUTSIDE the field room still takes.
	out.append(TestResult.new(
		"passing no site and no conditions at all leaves it where it was",
		course.fingerprint() == PRE_FIELD_DEFAULT_FINGERPRINT,
		"%s (was %s)" % [course.fingerprint(), PRE_FIELD_DEFAULT_FINGERPRINT]))

	# The same value the air slice pinned months before the field room existed, asserted through
	# ITS constant rather than through this file's copy — so the two cannot drift apart silently.
	out.append(TestResult.new(
		"and it is still the value test_air_density.gd has pinned since before any of this",
		PRE_FIELD_DEFAULT_FINGERPRINT == TestAirDensity.PRE_AIR_DEFAULT_FINGERPRINT,
		"%s vs %s" % [PRE_FIELD_DEFAULT_FINGERPRINT, TestAirDensity.PRE_AIR_DEFAULT_FINGERPRINT]))
	return out


# ---------------------------------------------------------------------------
# 3. The migration moved where a course IS without moving what it hashes to
# ---------------------------------------------------------------------------

static func _migration_keeps_the_hash() -> Array:
	var out: Array = []
	var migrated := _migrate_the_v1_fixture()
	var library := CourseLibrary.load_from(SCRATCH_COURSES)

	for pair in [["default_circuit", PRE_FIELD_DEFAULT_FINGERPRINT],
			["leh_circuit", PRE_FIELD_LEH_FINGERPRINT]]:
		var id: String = pair[0]
		var before: String = pair[1]
		var course := library.course(id)
		out.append(TestResult.new(
			"the migrated library still holds \"%s\"" % id, course != null,
			"%s" % [library.ids()]))
		if course == null:
			continue
		var site: Site = migrated.site(course.site_id)
		out.append(TestResult.new(
			"\"%s\" was given a site by the migration" % id, site != null,
			"site_id %s" % course.site_id))
		if site == null:
			continue
		var conditions := _conditions_for(site)
		var after := course.fingerprint(AirDensity.compose(site, conditions), site, conditions)
		out.append(TestResult.new(
			"\"%s\" hashes after migration to exactly what it hashed to before it" % id,
			after == before, "%s (was %s)" % [after, before]))

	# The one thing about the migrated sites this hash depends on, asserted directly rather than
	# inferred from the hash matching: a migration that stamped an elevation onto a sea-level
	# course would change the rho term, and a hash that still matched would mean the site was not
	# reaching the hash at all.
	var flat_course := library.course("default_circuit")
	if flat_course != null:
		var flat_site: Site = migrated.site(flat_course.site_id)
		if flat_site != null:
			out.append(TestResult.new(
				"the sea-level v1 course was migrated to a sea-level site, not to a stamped one",
				absf(flat_site.elevation_m) < SAME_S,
				"%.3f m" % flat_site.elevation_m))
			out.append(TestResult.new(
				"and to ground that is flat at zero, so no terrain term is owed",
				flat_site.terrain.is_flat_at_zero(), "shape %s" % flat_site.terrain.shape))
	return out


# ---------------------------------------------------------------------------
# 4. Terrain reaches the hash, dimensions and all
# ---------------------------------------------------------------------------

static func _terrain_reaches_the_hash() -> Array:
	var out: Array = []
	var course := GateCourse.new(GateCourse.build_gates())
	var calm := Conditions.standard()

	var flat_site := Site.new()
	var flat_hash := course.fingerprint(AirDensity.compose(flat_site, calm), flat_site, calm)

	var gentle := _sloped_site(1.0)
	var steep := _sloped_site(6.0)
	var gentle_hash := course.fingerprint(AirDensity.compose(gentle, calm), gentle, calm)
	var steep_hash := course.fingerprint(AirDensity.compose(steep, calm), steep, calm)

	# THE GUARD BEFORE THE COMPARISONS: both sites must actually be non-flat, or all three hashes
	# below are the flat one and "gentle != steep" is comparing a string with itself.
	out.append(TestResult.new(
		"both sloped sites really are non-flat, so the comparisons below have something to compare",
		not gentle.terrain.is_flat_at_zero() and not steep.terrain.is_flat_at_zero()
			and gentle.terrain.fingerprint_term() != steep.terrain.fingerprint_term(),
		"%s vs %s" % [gentle.terrain.fingerprint_term(), steep.terrain.fingerprint_term()]))

	out.append(TestResult.new(
		"a non-flat site changes the hash",
		gentle_hash != flat_hash, "%s vs flat %s" % [gentle_hash, flat_hash]))
	out.append(TestResult.new(
		"two slopes differing only in their rise hash differently",
		gentle_hash != steep_hash, "1 m %s vs 6 m %s" % [gentle_hash, steep_hash]))
	out.append(TestResult.new(
		"and a slope is not confused with a bowl of the same size",
		course.fingerprint(AirDensity.compose(_bowl_site(), calm), _bowl_site(), calm)
			!= gentle_hash,
		"%s vs %s" % [course.fingerprint(AirDensity.compose(_bowl_site(), calm), _bowl_site(), calm),
			gentle_hash]))
	return out


# ---------------------------------------------------------------------------
# 5. F3's carry-forward, pinned so a later slice cannot change it by accident
# ---------------------------------------------------------------------------

static func _an_unreadable_shape_is_flat() -> Array:
	var out: Array = []
	var course := GateCourse.new(GateCourse.build_gates())
	var calm := Conditions.standard()

	var flat_site := Site.new()
	var flat_hash := course.fingerprint(AirDensity.compose(flat_site, calm), flat_site, calm)

	# A shape name from a build newer than this one. `Terrain.from_data` maps it to FLAT, because
	# this build's `height_at` genuinely answers 0 everywhere for geometry it cannot evaluate.
	var newer := Site.new()
	newer.terrain = Terrain.from_data({"shape": "canyon", "width_m": Terrain.DEFAULT_WIDTH_M,
		"length_m": Terrain.DEFAULT_LENGTH_M, "depth_m": 9.0})
	var other := Site.new()
	other.terrain = Terrain.from_data({"shape": "volcano", "width_m": Terrain.DEFAULT_WIDTH_M,
		"length_m": Terrain.DEFAULT_LENGTH_M, "rise_m": 40.0})

	out.append(TestResult.new(
		"a shape this build cannot read reads as flat, so no terrain term is appended for it",
		newer.terrain.is_flat_at_zero()
			and course.fingerprint(AirDensity.compose(newer, calm), newer, calm) == flat_hash,
		"%s" % course.fingerprint(AirDensity.compose(newer, calm), newer, calm)))
	# The consequence, written down rather than discovered: this build cannot tell them apart, and
	# must not be "fixed" into hashing geometry it cannot compute.
	out.append(TestResult.new(
		"and two DIFFERENT unreadable shapes hash identically here — the documented consequence",
		course.fingerprint(AirDensity.compose(newer, calm), newer, calm)
			== course.fingerprint(AirDensity.compose(other, calm), other, calm),
		"%s vs %s" % [course.fingerprint(AirDensity.compose(newer, calm), newer, calm),
			course.fingerprint(AirDensity.compose(other, calm), other, calm)]))
	return out


# ---------------------------------------------------------------------------
# 6. Wind reaches the hash — the speed AND the bearing
# ---------------------------------------------------------------------------

static func _wind_reaches_the_hash() -> Array:
	var out: Array = []
	var course := GateCourse.new(GateCourse.build_gates())
	var here := Site.new()
	var calm := Conditions.standard()
	var calm_hash := course.fingerprint(AirDensity.compose(here, calm), here, calm)

	var windy := _windy()
	var windy_hash := course.fingerprint(AirDensity.compose(here, windy), here, windy)
	out.append(TestResult.new(
		"a steady wind changes the hash",
		windy_hash != calm_hash, "%s vs calm %s" % [windy_hash, calm_hash]))

	# The same speed from somewhere else. A 6 m/s headwind down the back straight and a 6 m/s
	# tailwind down it are not the same lap, and a hash that took only the speed would say they are.
	var turned := _windy()
	turned.wind_from_deg = TEST_WIND_FROM_DEG + 180.0
	var turned_hash := course.fingerprint(AirDensity.compose(here, turned), here, turned)
	out.append(TestResult.new(
		"a different bearing at the same speed changes it too",
		turned_hash != windy_hash
			and absf(turned.wind_speed_mps - windy.wind_speed_mps) < SAME_S,
		"%s vs %s at %.2f m/s" % [turned_hash, windy_hash, turned.wind_speed_mps]))

	# And the quantisation holds on the side it has to: a bearing read back out of JSON a
	# ten-thousandth of a degree different is the same day.
	var jittered := _windy()
	jittered.wind_from_deg = TEST_WIND_FROM_DEG + 0.0001
	jittered.wind_speed_mps = TEST_WIND_MPS + 0.0001
	out.append(TestResult.new(
		"a float's round trip through JSON does not retire the record",
		course.fingerprint(AirDensity.compose(here, jittered), here, jittered) == windy_hash,
		"%s vs %s" % [course.fingerprint(AirDensity.compose(here, jittered), here, jittered),
			windy_hash]))
	return out


# ---------------------------------------------------------------------------
# 7. Gustiness is not in the hash, and the gate must not let it in by a side door
# ---------------------------------------------------------------------------

static func _gustiness_does_not() -> Array:
	var out: Array = []
	var course := GateCourse.new(GateCourse.build_gates())
	var here := Site.new()
	var calm := Conditions.standard()
	var calm_hash := course.fingerprint(AirDensity.compose(here, calm), here, calm)

	var gusty := Conditions.standard()
	gusty.gustiness_mps = TEST_GUSTINESS_MPS

	# THE GUARD, and it is not decoration. `is_calm()` COUNTS gustiness, so this set is correctly
	# not calm — and gating the wind append on `not is_calm()` would therefore append `wind=0,0`
	# and orphan every record on the course for a number that never reached the hash. That is the
	# whole reason `has_steady_wind()` exists. Both predicates are CALLED here so the check cannot
	# pass by the two of them having quietly become the same function.
	out.append(TestResult.new(
		"a gust with no steady wind under it is NOT calm, and HAS no steady wind",
		not gusty.is_calm() and not gusty.has_steady_wind(),
		"is_calm=%s has_steady_wind=%s" % [gusty.is_calm(), gusty.has_steady_wind()]))

	out.append(TestResult.new(
		"gustiness alone does not change the hash",
		course.fingerprint(AirDensity.compose(here, gusty), here, gusty) == calm_hash,
		"%s vs calm %s" % [course.fingerprint(AirDensity.compose(here, gusty), here, gusty),
			calm_hash]))

	# And it does not change it on top of a wind either — the term is the steady figure, whatever
	# the noise around it is doing.
	var windy := _windy()
	var windy_and_gusty := _windy()
	windy_and_gusty.gustiness_mps = TEST_GUSTINESS_MPS
	out.append(TestResult.new(
		"nor does adding it to a day that already has a steady wind",
		course.fingerprint(AirDensity.compose(here, windy_and_gusty), here, windy_and_gusty)
			== course.fingerprint(AirDensity.compose(here, windy), here, windy),
		"%s vs %s" % [
			course.fingerprint(AirDensity.compose(here, windy_and_gusty), here, windy_and_gusty),
			course.fingerprint(AirDensity.compose(here, windy), here, windy)]))
	return out


# ---------------------------------------------------------------------------
# 8. The regression this slice is most likely to cause: losing the rho term
# ---------------------------------------------------------------------------

static func _the_rho_term_still_lands() -> Array:
	var out: Array = []
	var course := GateCourse.new(GateCourse.build_gates())
	var here := Site.new()

	var calm := Conditions.standard()
	var warm := Conditions.standard()
	warm.temperature_c = 35.0
	var warm_air := AirDensity.compose(here, warm)

	# The guard: a hot day must actually be non-standard air, or every comparison below is between
	# two copies of the standard hash.
	out.append(TestResult.new(
		"a calm 35 °C day at sea level is genuinely not standard air",
		not warm_air.is_standard() and warm.is_calm(),
		"%.4f kg/m3" % warm_air.kgm3()))

	var warm_hash := course.fingerprint(warm_air, here, warm)
	out.append(TestResult.new(
		"calm-but-warm conditions change the hash",
		warm_hash != course.fingerprint(AirDensity.compose(here, calm), here, calm),
		"%s vs %s" % [warm_hash,
			course.fingerprint(AirDensity.compose(here, calm), here, calm)]))
	# VIA THE RHO TERM ONLY: the same air with no site and no conditions passed gives the same
	# hash, so the temperature is still reaching it the way it always did and not through a new
	# door. If the rho term were dropped now that air is composed, both sides collapse to the
	# geometry-only hash and the check above goes red with it.
	out.append(TestResult.new(
		"and it changes it through the rho term, exactly as it did before any of this",
		warm_hash == course.fingerprint(warm_air),
		"%s vs %s" % [warm_hash, course.fingerprint(warm_air)]))
	return out


# ---------------------------------------------------------------------------
# 9. Which predicates gate the appends
# ---------------------------------------------------------------------------

static func _two_predicates_gate_the_appends() -> Array:
	var out: Array = []

	# CALLED, not merely named. A source scan that agrees with a function which does not exist is
	# the check that cannot fail; these two lines are what make the scan below mean anything.
	out.append(TestResult.new(
		"Terrain.is_flat_at_zero() answers the question the gate asks it",
		Terrain.flat(Terrain.DEFAULT_WIDTH_M, Terrain.DEFAULT_LENGTH_M).is_flat_at_zero()
			and not Terrain.shaped(Terrain.SLOPE, 40.0, 40.0, {"rise_m": 3.0}).is_flat_at_zero(),
		"flat=%s slope=%s" % [
			Terrain.flat(Terrain.DEFAULT_WIDTH_M, Terrain.DEFAULT_LENGTH_M).is_flat_at_zero(),
			Terrain.shaped(Terrain.SLOPE, 40.0, 40.0, {"rise_m": 3.0}).is_flat_at_zero()]))
	var breezy := Conditions.standard()
	breezy.wind_speed_mps = TEST_WIND_MPS
	out.append(TestResult.new(
		"Conditions.has_steady_wind() answers the question the other gate asks it",
		breezy.has_steady_wind() and not Conditions.standard().has_steady_wind(),
		"breezy=%s standard=%s" % [breezy.has_steady_wind(),
			Conditions.standard().has_steady_wind()]))

	var body := _fingerprint_body()
	# THE GUARD BEFORE THE SCAN. An empty body scans clean for everything, so the extraction must
	# be proved to have found the real function first — by a line only this function contains.
	out.append(TestResult.new(
		"the source scan actually found fingerprint()'s body",
		"\n".join(body).contains("sha256_text") and body.size() > 10,
		"%d code lines" % body.size()))

	var gates: Array[String] = []
	for line in body:
		var trimmed := (line as String).strip_edges()
		if trimmed.begins_with("if "):
			gates.append(trimmed)
	out.append(TestResult.new(
		"exactly three conditions gate the three optional terms",
		gates.size() == 3, "%s" % [gates]))
	if gates.size() != 3:
		return out

	out.append(TestResult.new(
		"the air term is gated on is_standard(), as it always was",
		gates[0].contains("p_air.is_standard()"), gates[0]))
	out.append(TestResult.new(
		"the terrain term is gated on is_flat_at_zero() and nothing else",
		gates[1].contains("is_flat_at_zero()")
			and not gates[1].contains("is_calm")
			and not gates[1].contains("wind"),
		gates[1]))
	out.append(TestResult.new(
		"the wind term is gated on has_steady_wind() and nothing else",
		gates[2].contains("has_steady_wind()")
			and not gates[2].contains("is_calm")
			and not gates[2].contains("wind_speed_mps"),
		gates[2]))
	# The one that says WHY there is a second predicate: `is_calm()` counts gustiness, so a gate
	# written on it would put a number the hash deliberately excludes back in charge of the hash.
	out.append(TestResult.new(
		"is_calm() does not gate anything in fingerprint()",
		not "\n".join(body).contains("is_calm"), "%s" % [gates]))
	return out


## `fingerprint()`'s body as CODE lines only — comment lines stripped, because the comments beside
## the gates discuss `is_calm()` at length and a scan that read them would answer about the prose.
static func _fingerprint_body() -> Array[String]:
	var out: Array[String] = []
	var file := FileAccess.open("res://src/course/gate_course.gd", FileAccess.READ)
	if file == null:
		return out
	var lines := file.get_as_text().split("\n")
	file.close()
	var inside := false
	for line in lines:
		var text := String(line)
		if text.begins_with("func fingerprint("):
			inside = true
			continue
		if not inside:
			continue
		# The next top-level declaration ends the body.
		if text.length() > 0 and not text.begins_with("\t") and not text.begins_with(" "):
			break
		var trimmed := text.strip_edges()
		if trimmed == "" or trimmed.begins_with("#"):
			continue
		out.append(text)
	return out


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

## The v1 fixture put at a scratch path and run through F1's migration, which REWRITES the file it
## is handed — hence the copy, and hence never the real `CourseLibrary.SAVE_PATH`.
static func _migrate_the_v1_fixture() -> SiteLibrary:
	_clean_scratch()
	_copy(COURSES_V1_FIXTURE, SCRATCH_COURSES)
	return SiteLibrary.migrate_courses(SCRATCH_COURSES, SCRATCH_SITES)


## The conditions a migrated site is flown in: the temperature the migration PARKED on it, which
## is the other half of the air its v1 `air` block described. A site with nothing parked was a
## course with no `air` block, and standard is the correct reading of that silence.
static func _conditions_for(p_site: Site) -> Conditions:
	var out := Conditions.standard()
	if p_site.parked_temperature_c != null:
		out.temperature_c = float(p_site.parked_temperature_c)
	return out


static func _windy() -> Conditions:
	var out := Conditions.standard()
	out.wind_speed_mps = TEST_WIND_MPS
	out.wind_from_deg = TEST_WIND_FROM_DEG
	return out


static func _sloped_site(rise_m: float) -> Site:
	var out := Site.new()
	out.terrain = Terrain.shaped(Terrain.SLOPE, 80.0, 80.0, {"rise_m": rise_m, "direction_deg": 0.0})
	return out


static func _bowl_site() -> Site:
	var out := Site.new()
	out.terrain = Terrain.shaped(Terrain.BOWL, 80.0, 80.0, {"depth_m": 1.0})
	return out


static func _copy(from_path: String, to_path: String) -> void:
	var source := FileAccess.open(from_path, FileAccess.READ)
	if source == null:
		return
	var text := source.get_as_text()
	source.close()
	var target := FileAccess.open(to_path, FileAccess.WRITE)
	if target == null:
		return
	target.store_string(text)
	target.close()


static func _clean_scratch() -> void:
	for path in [SCRATCH_BEST_LAPS, SCRATCH_COURSES, SCRATCH_SITES]:
		if FileAccess.file_exists(path):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
