class_name TestPropulsionPanel
extends RefCounted
## The propeller inspector's blade-geometry rows — the P0–P2 numbers, on screen.
##
## ## Why these rows are tested through the panel and not through BladeGeometry
##
## `test_blade_geometry.gd` already proves the integrals against their closed forms. What it cannot
## prove is that the right integral reaches the screen wearing the right caveat, and that is the
## whole risk here. propulsion.md §3.1 draws a distinction the panel is the only place to get wrong:
##
##   - **Thrust is protected by §4.4's calibration; inertia is not.** A generated planform that is
##     15% too fat barely moves k², but the generator's SHAPE is wrong — its arch peaks at ≈0.46 R,
##     inboard of every real FPV planform — so its k² ≈ 0.278 sits BELOW the plausible band
##     [0.358, 0.460]. A spin-up figure built on it is low by that factor.
##   - **So the inertia on screen must be built from the PUBLISHED mass times the shape-only k²**,
##     never from the generated blade mass, which §3.1 measured at 0.17–1.18× published. Using the
##     computed mass would multiply two errors and look completely plausible doing it.
##
## `_test_inertia_uses_published_mass_not_computed` is the load-bearing test in this file: it fails
## if the panel takes the tempting shortcut, and nothing else in the suite would notice.
##
## The seam is `detail_text()` / `blade_row_text()`, which is the same call `render_rows()` makes —
## asserting against the source data instead would test the catalog twice and the panel not at all.

static func run() -> Array:
	var results: Array = []
	var catalog := PartsCatalog.load_default()
	var materials := FrameMaterials.load_default()
	var panel := PropellerDetails.new(PartsCatalog.load_default())

	results.append(_test_every_blade_row_renders_for_every_prop(catalog, panel))
	results.append(_test_a_generated_planform_is_labelled_assumed_everywhere(catalog, panel))
	results.append(_test_an_authored_planform_carries_no_caveat(materials))
	results.append(_test_inertia_uses_published_mass_not_computed(materials))
	results.append(_test_the_mass_gap_reports_the_p1_finding(catalog, panel))
	results.append(_test_a_blade_nobody_published_shows_no_gap(materials))
	results.append(_test_the_generated_shape_is_reported_below_the_band(catalog, panel))

	panel.free()
	return results


## The blade rows this file is about — the ones PropellerDetails gained for P0–P2.
const BLADE_KEYS := ["planform", "blade_mass", "mass_gap", "k2", "blade_inertia"]


## Every catalog prop must render a real string in every blade row. The failure this catches is a
## row that silently answers "—" for a whole class of props — the same check the Airframe tabs run
## across every catalog frame, and for the same reason: a dash is indistinguishable from a value
## nobody looked at.
static func _test_every_blade_row_renders_for_every_prop(catalog: PartsCatalog, panel: PropellerDetails) -> TestResult:
	var bad: Array[String] = []
	var rendered := 0
	for prop in catalog.list_category("propeller"):
		for key in BLADE_KEYS:
			var text := panel.detail_text(prop, key)
			rendered += 1
			if text.strip_edges() == "" or text == "—" or text.begins_with("0 ") or text == "nan":
				bad.append("%s/%s='%s'" % [prop.get("part_id", "?"), key, text])
	return TestResult.new(
		"every blade row renders a real number for every catalog propeller",
		bad.is_empty() and rendered == 19 * BLADE_KEYS.size(),
		"%d rows rendered; bad: %s" % [rendered, "none" if bad.is_empty() else ", ".join(bad)])


## §3.1: every figure derived from a generated planform says so, in the wording A7 established.
## A preset is generated by construction, so no blade row on any catalog prop may go unlabelled.
static func _test_a_generated_planform_is_labelled_assumed_everywhere(catalog: PartsCatalog, panel: PropellerDetails) -> TestResult:
	var unlabelled: Array[String] = []
	for prop in catalog.list_category("propeller"):
		for key in ["blade_mass", "k2", "blade_inertia"]:
			var text := panel.detail_text(prop, key)
			if not text.contains("(assumed)"):
				unlabelled.append("%s/%s" % [prop.get("part_id", "?"), key])
	return TestResult.new(
		"every figure from a generated planform carries the assumed-chord caveat",
		unlabelled.is_empty(),
		"unlabelled: %s" % ["none" if unlabelled.is_empty() else ", ".join(unlabelled)])


## The other half, and the half that makes the caveat mean something: a planform the builder drew is
## NOT assumed, and its rows must be clean. A panel that stamped the caveat unconditionally would
## pass the test above and be useless.
static func _test_an_authored_planform_carries_no_caveat(materials: FrameMaterials) -> TestResult:
	var doc := _authored_doc()
	var texts: Array[String] = []
	for key in ["blade_mass", "k2", "blade_inertia"]:
		texts.append(PropellerDetails.blade_row_text(key, doc, materials))
	var clean := not PropellerDetails.blade_note_text(doc, materials).contains("generated chord")
	for t in texts:
		if t.contains("assumed"):
			clean = false
	return TestResult.new(
		"a planform the builder drew carries no assumed-chord caveat",
		clean,
		" / ".join(texts) + " ; note: " + PropellerDetails.blade_note_text(doc, materials))


## THE LOAD-BEARING TEST. §3.1: "the spin-up number that matters is built from the *published* mass
## times the shape-only k²". The computed blade mass is 0.17–1.18× published because the hub is
## unmodelled, so an inertia built from it inherits that error on top of the shape error.
##
## Built to FAIL if the panel uses `BladeGeometry.blade_inertia_kg_m2` (the computed-mass form)
## instead: the document below has a deliberately absurd thickness_ratio, which moves the computed
## mass by 5× and must move the number on screen by NOTHING, because published mass and k² are both
## independent of it.
static func _test_inertia_uses_published_mass_not_computed(materials: FrameMaterials) -> TestResult:
	var thin := _authored_doc()
	thin.thickness_ratio = 0.02
	var fat := _authored_doc()
	fat.thickness_ratio = 0.10

	var thin_text := PropellerDetails.blade_row_text("blade_inertia", thin, materials)
	var fat_text := PropellerDetails.blade_row_text("blade_inertia", fat, materials)

	# And the value itself must be m_published·k²·R², to the digit shown.
	var k2 := BladeGeometry.radius_of_gyration_sq(fat)
	var radius_m := fat.radius_mm() * 0.001
	var expected := fat.published_mass_g * 0.001 * k2 * radius_m * radius_m
	var expected_text := "%.1f g·cm²" % (expected * 1.0e7)

	return TestResult.new(
		"blade inertia is published mass × k² × R², so section thickness cannot move it",
		thin_text == fat_text and fat_text.contains(expected_text),
		"t/c 0.02 -> %s ; t/c 0.10 -> %s ; want %s" % [thin_text, fat_text, expected_text])


## P1's finding, on screen rather than in a test log. §9a's precedent: the disagreement is reported,
## with its diagnosis travelling alongside, and nothing is tuned to close it.
static func _test_the_mass_gap_reports_the_p1_finding(catalog: PartsCatalog, panel: PropellerDetails) -> TestResult:
	# The 16x12x4 whoop prop is the worst case in the band (-83%) and it is worst because the hub is
	# the largest share of a small prop — which is exactly what the row's note must say.
	var prop := _prop_by_id(catalog, "prop_16x12x4")
	var cell := panel.detail_text(prop, "mass_gap")
	var note := PropellerDetails.blade_note_text(PropellerDetails.document_for(prop), PropellerDetails.materials())
	return TestResult.new(
		"the mass gap prints the disagreement, and the note names the hub as the reason",
		cell.contains("-83") and note.contains("the hub is not modelled"),
		"%s / %s" % [cell, note])


## A blade somebody drew has no vendor to disagree with. That is not a missing value and must not
## render as a gap against zero — StructureDetails' rule, transplanted.
static func _test_a_blade_nobody_published_shows_no_gap(materials: FrameMaterials) -> TestResult:
	var doc := _authored_doc()
	doc.published_mass_g = 0.0
	var gap := PropellerDetails.blade_row_text("mass_gap", doc, materials)
	var inertia := PropellerDetails.blade_row_text("blade_inertia", doc, materials)
	return TestResult.new(
		"a blade with no vendor figure shows no gap, and no inertia it cannot honestly build",
		gap.contains("yours") and not gap.contains("%"),
		"gap %s / inertia %s" % [gap, inertia])


## §3.3's finding, which is the reason presets are characteristic rather than engineering-grade: the
## generator's arch peaks at ≈0.46 R and lands k² ≈ 0.278, BELOW the plausible band. The panel must
## say that out loud — a k² quoted with no relation to the band is a number nobody can interpret.
static func _test_the_generated_shape_is_reported_below_the_band(catalog: PartsCatalog, panel: PropellerDetails) -> TestResult:
	var prop := _prop_by_id(catalog, "prop_5x43x3")
	var cell := panel.detail_text(prop, "k2")
	var note := PropellerDetails.blade_note_text(PropellerDetails.document_for(prop), PropellerDetails.materials())
	return TestResult.new(
		"k² is quoted against the plausible band, and the generated shape is flagged below it",
		cell.contains("0.278") and note.contains("below the 0.358–0.460 band"),
		"%s / %s" % [cell, note])


# ---------------------------------------------------------------------------

## A planform inside §3.3's plausible family — root-tapered, peak at 0.68 R, 10% tip — with a vendor
## mass, and NOT flagged assumed. This is what a builder who drew their own blade has.
static func _authored_doc() -> PropellerDocument:
	var doc := PropellerDocument.new()
	doc.name = "Drawn blade"
	doc.diameter_mm = 127.0
	doc.pitch_mm = 109.22
	doc.blades = 3
	doc.material_id = "polycarbonate"
	doc.thickness_ratio = 0.10
	doc.published_mass_g = 4.5
	doc.chord_is_assumed = false
	var hub := 0.10
	var peak := 0.68
	var n := 40
	doc.chord.append(hub)
	doc.chord.append(0.0)
	for i in n + 1:
		var x: float = hub + (1.0 - hub) * float(i) / float(n)
		var c: float = (x - hub) / (peak - hub) if x <= peak else 1.0 - 0.90 * (x - peak) / (1.0 - peak)
		doc.chord.append(x)
		doc.chord.append(c * 13.0)
	return doc


static func _prop_by_id(catalog: PartsCatalog, part_id: String) -> Dictionary:
	for prop in catalog.list_category("propeller"):
		if str(prop.get("part_id", "")) == part_id:
			return prop
	return {}
