class_name PrintedDivergence
extends RefCounted
## Divergence on open — printed-room slice PR5 (persistence design §7.5).
##
## A printed part is a fact about this drone: PLA and TPU do not recompute. So when a drone is opened,
## every part it has printed is generated again from the build as it stands and compared, by hash, with
## the NEWEST record for that part. Four outcomes:
##
##   - **matches** — nothing is said. The silent path is the common one and must stay silent.
##   - **differs** — dated, keep-or-reprint, and every cause the record can prove: a camera tilt from/to
##     (the tilt is ONE global setting, so moving it changes every drone's camera mount, and a bare
##     "differs" would leave the builder hunting a change they never made to this drone), a clearance
##     from/to, a generator version from/to. When none of those explains it, it says the parts or
##     settings the part is made from changed.
##   - **gone** — the build no longer lists the part, or refuses it today. Reported; the record is kept.
##   - **missing_file** — the record's `printed/` member is not in the drone. Reported, never dropped.
##
## Nothing is reprinted and nothing is deleted. Reprinting is "Export printed parts…"; keeping is doing
## nothing. Keep/reprint buttons are deferred (plan, PR5).

const LABELS := {
	"arm_guard": "arm guard",
	"camera_mount": "camera mount",
	"antenna_mount": "antenna mount",
	"prop_guard": "prop guard",
}


## One finding per part that needs saying: `{"part", "kind", "message"}`.
static func check(project: Project, container: ProjectContainer, build: Build,
		prop_tip_radius_m: float) -> Array:
	var findings: Array = []
	if project == null or build == null:
		return findings

	# Newest record per part: records are appended in export order, so the last one wins.
	var newest: Dictionary = {}
	var order: Array = []
	for raw in project.print_records:
		if not raw is Dictionary:
			continue
		var part := String((raw as Dictionary).get("part", ""))
		if part == "":
			continue
		if not newest.has(part):
			order.append(part)
		newest[part] = raw

	var listed: Dictionary = {}
	for row in PrintedParts.for_build(build):
		listed[String(row["id"])] = true

	for part in order:
		var record: Dictionary = newest[part]
		var label := String(LABELS.get(part, part))
		var date := String(record.get("printed_at", "")).substr(0, 10)
		var file := String(record.get("file", ""))

		if container != null and container.member_bytes(file).is_empty():
			findings.append({"part": part, "kind": "missing_file",
				"message": "The %s printed on %s is recorded, but its file %s is missing from this drone." % [
					label, date, file]})
			continue

		var solid := PrintedParts.solid_for(build, part, prop_tip_radius_m) if listed.has(part) else {}
		if not listed.has(part) or not bool(solid.get("ok", false)):
			var why := "this build does not list it" if not listed.has(part) else String(solid.get("reason", ""))
			findings.append({"part": part, "kind": "gone",
				"message": "The %s printed on %s is no longer generated by this build (%s). Its record is kept." % [
					label, date, why]})
			continue

		var text := StlWriter.to_ascii(PrintedExport.safe_name(String(solid["solid_name"])), solid["triangles"])
		if text.sha256_text() == String(record.get("geometry_sha256", "")):
			continue

		findings.append({"part": part, "kind": "differs",
			"message": "The %s you printed on %s differs from what this build now generates (%s). Keep the printed one, or reprint it?" % [
				label, date, "; ".join(PackedStringArray(_causes(record, solid, build)))]})
	return findings


## Every cause the record can prove, as "x changed from a to b". Never empty.
static func _causes(record: Dictionary, solid: Dictionary, build: Build) -> Array:
	var causes: Array = []
	if record.has("tilt_deg") and (solid.get("inputs", {}) as Dictionary).has("tilt_deg"):
		var was := float(record["tilt_deg"])
		var now := float(solid["inputs"]["tilt_deg"])
		if absf(was - now) > 1e-6:
			causes.append("the camera tilt changed from %s° to %s° — the tilt is shared by every drone" % [
				_deg(was), _deg(now)])
	if record.has("clearance_mm"):
		var was_c := float(record["clearance_mm"])
		var now_c := PrintSettings.clearance_mm(build.printing)
		if absf(was_c - now_c) > 1e-6:
			causes.append("clearance changed from %.2f to %.2f mm" % [was_c, now_c])
	var was_g := String(record.get("generator", ""))
	var now_g := String(solid.get("generator", ""))
	if was_g != "" and was_g != now_g:
		causes.append("generator changed from %s to %s" % [was_g, now_g])
	if causes.is_empty():
		causes.append("the parts or settings it is made from changed")
	return causes


## 25 and 40 as "25" and "40"; 32.5 as "32.5".
static func _deg(value: float) -> String:
	return str(int(round(value))) if absf(value - round(value)) < 1e-6 else "%.1f" % value
