class_name PrintedDivergence
extends RefCounted
## Divergence on open — printed-room slice PR5 (persistence design §7.5).
##
## A printed part is a fact about this drone: PLA and TPU do not recompute. So when a drone is opened,
## every part it has printed is generated again from the build as it stands and compared, by hash, with
## the NEWEST record for that part. Four outcomes:
##
##   - **matches** — nothing is said. The silent path is the common one and must stay silent.
##   - **differs** — dated, keep-or-reprint, and every cause the record can prove: a camera tilt from/to
##     (the tilt is ONE global setting, so moving it changes every drone's camera mount, and a bare
##     "differs" would leave the builder hunting a change they never made to this drone), a clearance
##     from/to, a generator version from/to. When none of those explains it, it says the parts or
##     settings the part is made from changed.
##   - **gone** — the build no longer lists the part, or refuses it today. Reported; the record is kept.
##   - **missing_file** — the record's `printed/` member is not in the drone. Reported, never dropped.
##
## Nothing is reprinted and nothing is deleted. Reprinting is "Export printed parts…"; keeping is doing
## nothing. Keep/reprint buttons are deferred (plan, PR5).

const LABELS := {
	"arm_guard": "arm guard",
	"camera_mount": "camera mount",
	"antenna_mount": "antenna mount",
	"prop_guard": "prop guard",
	"frame": "frame",
	"gps_mast": "GPS mast",
	"battery_pad": "battery pad",
}


## Where Keep is remembered, in the drone's own printing block (PR7) — so it travels with the file.
const KEPT := "divergence_kept"


## Keep: acknowledges ONE finding, by its key — part, the record's sha, and what the build generates
## today (or `gone` / `missing_file`). The record is never touched. A later, DIFFERENT divergence on the
## same part has a different key, so it speaks again: Keep is "I know about this one", not "stop telling
## me about this part".
static func acknowledge(printing: Dictionary, finding: Dictionary) -> void:
	var key := String(finding.get("key", ""))
	if key == "":
		return
	var kept: Array = (printing.get(KEPT, []) as Array).duplicate() if printing.get(KEPT) is Array else []
	if not kept.has(key):
		kept.append(key)
	printing[KEPT] = kept


static func is_kept(printing: Dictionary, key: String) -> bool:
	var kept: Variant = printing.get(KEPT, [])
	return kept is Array and (kept as Array).has(key)


## One finding per part that needs saying: `{"part", "kind", "message"}`.
static func check(project: Project, container: ProjectContainer, build: Build) -> Array:
	var findings: Array = []
	if project == null or build == null:
		return findings

	# Newest record per part: records are appended in export order, so the last one wins.
	var newest: Dictionary = {}
	var order: Array = []
	for raw in project.print_records:
		if not raw is Dictionary:
			continue
		var part := String((raw as Dictionary).get("part", ""))
		if part == "":
			continue
		if not newest.has(part):
			order.append(part)
		newest[part] = raw

	var listed: Dictionary = {}
	for row in PrintedParts.for_build(build):
		listed[String(row["id"])] = true

	for part in order:
		var record: Dictionary = newest[part]
		var label := String(LABELS.get(part, part))
		var date := String(record.get("printed_at", "")).substr(0, 10)
		var file := String(record.get("file", ""))

		var record_sha := String(record.get("geometry_sha256", ""))
		if container != null and container.member_bytes(file).is_empty():
			var missing_key := "%s|%s|missing_file" % [part, record_sha]
			if is_kept(build.printing, missing_key):
				continue
			findings.append({"part": part, "kind": "missing_file", "key": missing_key, "date": date,
				"message": "The %s printed on %s is recorded, but its file %s is missing from this drone." % [
					label, date, file]})
			continue

		var solid := PrintedParts.solid_for(build, part) if listed.has(part) else {}
		if not listed.has(part) or not bool(solid.get("ok", false)):
			var why := "this build does not list it" if not listed.has(part) else String(solid.get("reason", ""))
			var gone_key := "%s|%s|gone" % [part, record_sha]
			if is_kept(build.printing, gone_key):
				continue
			findings.append({"part": part, "kind": "gone", "key": gone_key, "date": date,
				"message": "The %s printed on %s is no longer generated by this build (%s). Its record is kept." % [
					label, date, why]})
			continue

		var text := StlWriter.to_ascii(PrintedExport.safe_name(String(solid["solid_name"])), solid["triangles"])
		var today := text.sha256_text()
		if today == record_sha:
			continue
		var differs_key := "%s|%s|%s" % [part, record_sha, today]
		if is_kept(build.printing, differs_key):
			continue

		findings.append({"part": part, "kind": "differs", "key": differs_key, "date": date,
			"message": "The %s you printed on %s differs from what this build now generates (%s). Keep the printed one, or reprint it?" % [
				label, date, "; ".join(PackedStringArray(_causes(record, solid, build)))]})
	return findings


## The findings as warnings, each owned by its part's Lab row (`WarningRows.item_of`): LIMITING —
## amber, because a print that no longer matches still flies; the builder decides Keep or Reprint.
## The long text is the finding's message, word for word.
static func warnings(findings: Array) -> Array[BuildWarning]:
	var out: Array[BuildWarning] = []
	for finding in findings:
		var values := {"part": String(finding.get("part", "")), "date": String(finding.get("date", ""))}
		var message := String(finding.get("message", ""))
		match String(finding.get("kind", "")):
			"differs":
				out.append(BuildWarning.limiting(&"printed_differs", message, values))
			"missing_file":
				out.append(BuildWarning.limiting(&"printed_missing_file", message, values))
			"gone":
				out.append(BuildWarning.limiting(&"printed_gone", message, values))
	return out


## Every cause the record can prove, as "x changed from a to b". Never empty.
static func _causes(record: Dictionary, solid: Dictionary, build: Build) -> Array:
	var causes: Array = []
	if record.has("tilt_deg") and (solid.get("inputs", {}) as Dictionary).has("tilt_deg"):
		var was := float(record["tilt_deg"])
		var now := float(solid["inputs"]["tilt_deg"])
		if absf(was - now) > 1e-6:
			causes.append("the camera tilt changed from %s° to %s° — the tilt is shared by every drone" % [
				_deg(was), _deg(now)])
	if record.has("mast_height_mm") and (solid.get("inputs", {}) as Dictionary).has("mast_height_mm"):
		var was_m := float(record["mast_height_mm"])
		var now_m := float(solid["inputs"]["mast_height_mm"])
		if absf(was_m - now_m) > 1e-6:
			causes.append("the GPS mast height changed from %.1f to %.1f mm — the mast is shared by every drone" % [
				was_m, now_m])
	if record.has("clearance_mm"):
		var was_c := float(record["clearance_mm"])
		var now_c := PrintSettings.clearance_mm(build.printing)
		if absf(was_c - now_c) > 1e-6:
			causes.append("clearance changed from %.2f to %.2f mm" % [was_c, now_c])
	var was_g := String(record.get("generator", ""))
	var now_g := String(solid.get("generator", ""))
	if was_g != "" and was_g != now_g:
		causes.append("generator changed from %s to %s" % [was_g, now_g])
	if causes.is_empty():
		causes.append("the parts or settings it is made from changed")
	return causes


## 25 and 40 as "25" and "40"; 32.5 as "32.5".
static func _deg(value: float) -> String:
	return str(int(round(value))) if absf(value - round(value)) < 1e-6 else "%.1f" % value
