extends SceneTree
## ONE-OFF FIXTURE GENERATOR FOR SLICE F9 — kept in the repo as the fixtures' provenance.
##
## `tests/fixtures/best_laps_pre_field.json` exists to prove that F9's terrain and wind terms do
## not orphan a best lap set before the field room existed. A fixture generated by the new code
## would be a test that cannot fail, so the two golden fingerprints in it are produced by the
## SHIPPED PRE-F1 `src/course/gate_course.gd`, read out of git and compiled at runtime:
##
##     git show 3a64a7b:src/course/gate_course.gd
##
## 3a64a7b is the parent of 9a8749e ("F1"), i.e. the last commit before any of the field room
## existed. The source is compiled with only its `class_name GateCourse` line removed — otherwise
## it would collide with the live class — and nothing else is touched. Its sole dependency is
## `AirDensity`, whose constructor, `is_standard()` and `kgm3()` are byte-identical at HEAD (the
## only change since 3a64a7b is the added `compose()`).
##
## The best-lap file itself is written by `LapTimer.save_best()`, which is ALSO unchanged since
## 3a64a7b — the same writer the game uses, pointed at an explicit path.
##
## `tests/fixtures/courses_pre_field_v1.json` is authored here in the v1 schema documented in
## pre-F1 `course_library.gd`'s own header (schema 1, an optional per-course `air` block). Its
## gates are checked below to re-hash, through the pre-F1 code, to the same two fingerprints the
## best-lap file is keyed on — so a hand-typo in the gate table cannot slip through.
##
## USAGE (HOME relocated exactly as tools/run_tests_safe.sh does it, so nothing can reach the
## developer's real user:// data):
##     scratch=$HOME/.lothal-fixture-home.$$; mkdir -p "$scratch"
##     HOME="$scratch" godot --headless --script res://tools/f9_make_fixture.gd
##     rm -rf "$scratch"

const PREFIELD_SOURCE_COMMIT := "3a64a7b"
const BEST_LAPS_OUT := "res://tests/fixtures/best_laps_pre_field.json"
const COURSES_OUT := "res://tests/fixtures/courses_pre_field_v1.json"
## A path under the relocated HOME's user:// — never the real best_laps.json, which is why
## LapTimer takes an injectable save path at all.
const SCRATCH_BEST_LAPS := "user://f9_fixture_best_laps.json"

## The two times, typed here. They are lap times, not derived quantities: nothing computes them.
const DEFAULT_CIRCUIT_BEST_S := 41.37
const LEH_CIRCUIT_BEST_S := 48.02

## The v1 `air` block on the second course. Leh, on a warm day — chosen so its rho is well away
## from standard and the pre-F1 hash therefore carries a `rho=` term, which is what makes the
## migration check in `tests/test_fingerprint_survival.gd` worth running.
const LEH_ELEVATION_M := 3500.0
const LEH_TEMPERATURE_C := 20.0

func _init() -> void:
	var source_path: String = OS.get_environment("F9_PREFIELD_GATE_COURSE")
	if source_path == "":
		push_error("F9_PREFIELD_GATE_COURSE must point at the `git show %s:src/course/gate_course.gd` output"
			% PREFIELD_SOURCE_COMMIT)
		quit(2)
		return

	var file := FileAccess.open(source_path, FileAccess.READ)
	if file == null:
		push_error("cannot read %s" % source_path)
		quit(2)
		return
	var source := file.get_as_text()
	file.close()

	# The ONE edit, and it is not to any line this fixture depends on: the global class
	# registration, which would collide with the live GateCourse.
	var stripped := source.replace("class_name GateCourse\n", "")
	if stripped == source:
		push_error("expected a `class_name GateCourse` line to strip — is this really the pre-F1 file?")
		quit(2)
		return

	var prefield := GDScript.new()
	prefield.source_code = stripped
	var status := prefield.reload()
	if status != OK:
		push_error("pre-F1 gate_course.gd did not compile: %d" % status)
		quit(2)
		return

	var default_circuit: Object = prefield.new(prefield.build_gates(), "default_circuit", "Circuit")
	var default_fp: String = default_circuit.fingerprint()

	var leh: Object = prefield.new(prefield.build_gates(), "leh_circuit", "Leh circuit")
	leh.air = AirDensity.new(LEH_ELEVATION_M, LEH_TEMPERATURE_C)
	var leh_fp: String = leh.fingerprint()

	if default_fp == leh_fp:
		push_error("the two fixture courses hash the same — the rho term did not land")
		quit(2)
		return

	# The best-lap file, written by the real LapTimer at an explicit path under the relocated HOME.
	if FileAccess.file_exists(SCRATCH_BEST_LAPS):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(SCRATCH_BEST_LAPS))
	var timer := LapTimer.new(default_fp, SCRATCH_BEST_LAPS)
	timer.best_lap_s = DEFAULT_CIRCUIT_BEST_S
	timer.save_best()
	var second := LapTimer.new(leh_fp, SCRATCH_BEST_LAPS)
	second.best_lap_s = LEH_CIRCUIT_BEST_S
	second.save_best()

	var written := FileAccess.open(SCRATCH_BEST_LAPS, FileAccess.READ)
	var best_laps_text := written.get_as_text()
	written.close()
	_write(BEST_LAPS_OUT, best_laps_text)

	# The v1 courses file. Gates taken from the same pre-F1 `gates_to_data`, so the table below is
	# not hand-typed geometry either.
	var v1 := {
		"schema": 1,
		"selected": "default_circuit",
		"courses": [
			{"id": "default_circuit", "name": "Circuit",
				"gates": prefield.gates_to_data(default_circuit.gates)},
			{"id": "leh_circuit", "name": "Leh circuit",
				"air": {"elevation_m": LEH_ELEVATION_M, "temperature_c": LEH_TEMPERATURE_C},
				"gates": prefield.gates_to_data(leh.gates)},
		],
	}
	_write(COURSES_OUT, JSON.stringify(v1, "\t") + "\n")

	# The round trip that makes the hand-authored wrapper safe: the gates as they now sit in the
	# file, read back through the PRE-F1 reader, must hash to the keys the best-lap file uses.
	for record in (v1["courses"] as Array):
		var entry: Dictionary = record
		var reread: Object = prefield.new(
			prefield.gates_from_data(entry["gates"]), String(entry["id"]), String(entry["name"]))
		if entry.has("air"):
			reread.air = AirDensity.from_data(entry["air"])
		var expected: String = default_fp if entry["id"] == "default_circuit" else leh_fp
		if reread.fingerprint() != expected:
			push_error("%s re-hashed to %s, expected %s" % [entry["id"], reread.fingerprint(), expected])
			quit(2)
			return

	print("default_circuit fingerprint (pre-F1): %s  best %.2f s" % [default_fp, DEFAULT_CIRCUIT_BEST_S])
	print("leh_circuit     fingerprint (pre-F1): %s  best %.2f s" % [leh_fp, LEH_CIRCUIT_BEST_S])
	print("wrote %s and %s" % [BEST_LAPS_OUT, COURSES_OUT])
	quit(0)

func _write(path: String, text: String) -> void:
	var out := FileAccess.open(path, FileAccess.WRITE)
	out.store_string(text)
	out.close()
