#!/usr/bin/env python3
"""Regenerates the crosscheck fixtures that pin the Rust spectrum to the Python one (LTHL-20).

    python3 tools/spectrum_oracle.py

Writes two files into tests/fixtures/:

    spectrum_signal.txt   one float per line — the samples both implementations are fed
    spectrum_oracle.json  what resonance_analysis.spectrogram makes of them

===============================================================================
WHY A CHECKED-IN GOLDEN AND NOT A LIVE CALL
===============================================================================

The Rust spectrum in rust/src/spectrum.rs is a SECOND IMPLEMENTATION of a law that already has
one, which logs.md names as the failure the recorder derives nothing in order to avoid. It ships
anyway because Godot has no numpy and a product that tells a builder to run a Python script is
not a product. tests/rust_crosscheck_tier2.gd is the precedent for what makes that acceptable:
something has to force the two to agree.

That something cannot be a live Python call from the Godot test suite. The suite runs headless in
CI on a machine with no numpy and no promise of a Python at all, and a crosscheck that is skipped
when the interpreter is missing is a crosscheck that will be skipped forever.

So Python runs HERE, by hand, and leaves its answer on disk. The suite compares against the file.
The cost is that the golden goes stale silently if resonance_analysis.spectrogram changes — so
the JSON records the constants it was generated under, and the suite asserts those match the
Rust ones. A drift in FRAME_SECONDS or OVERLAP_FRACTION fails loudly; a drift in the windowing
itself is caught the next time this is run, which is what the header line in the JSON is for.

===============================================================================
WHAT THE SIGNAL IS, AND WHY IT IS NOT A RECORDED FLIGHT
===============================================================================

A real Lothal log would be a better fixture in one way and a much worse one in three: it is tens
of megabytes, it is regenerated by any change to the sim, and its content depends on a build.
This fixture has to be stable for years and readable by a human who wants to know what the
crosscheck is actually checking.

So it is built to exercise the three things the two implementations could disagree about:

  * a SWEEPING tone, so per-frame framing errors show up as a smeared peak rather than as nothing
  * a FIXED tone at 183.4 Hz, the number the report pane's caveat is written about, so an
    off-by-one in the frame layout moves it visibly
  * a DC OFFSET of 3.0, which is invisible unless the per-frame mean removal is missing — and if
    it is missing, bin 0 and its Hann sidelobes carry the offset instead

The offset is the one worth stating. Detrending is a choice, not a default, and an implementation
that skipped it would still produce a plausible-looking spectrum that agreed with Python
everywhere except the first few bins — which is where a slow log's structure lives.
"""

from __future__ import annotations

import json
import math
import pathlib
import random
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import numpy as np

from resonance_analysis import FRAME_SECONDS, OVERLAP_FRACTION, spectrogram

FIXTURES = pathlib.Path(__file__).resolve().parent.parent / "tests" / "fixtures"

SAMPLE_RATE_HZ = 1000.0
DURATION_S = 6.0
#: The frame mode the report pane marks. Fixed, so a framing error moves it.
MODE_HZ = 183.4
#: A 1x line sweeping 90 -> 260 Hz, which crosses the mode the way a spool-up does.
SWEEP_FROM_HZ = 90.0
SWEEP_TO_HZ = 260.0
#: Removed by per-frame detrending, and by nothing else.
DC_OFFSET = 3.0
#: Seeded, because a fixture that differs per run cannot be a golden.
SEED = 20260816
NOISE_SD = 0.02


def signal() -> list[float]:
    rng = random.Random(SEED)
    n = int(round(DURATION_S * SAMPLE_RATE_HZ))
    out = []
    for i in range(n):
        t = i / SAMPLE_RATE_HZ
        # Phase is the integral of a linear frequency ramp, not f(t) * t — the second is the
        # classic chirp bug and it puts the instantaneous frequency at twice the intended rate.
        rate = (SWEEP_TO_HZ - SWEEP_FROM_HZ) / DURATION_S
        phase = 2.0 * math.pi * (SWEEP_FROM_HZ * t + 0.5 * rate * t * t)
        out.append(
            DC_OFFSET
            + math.sin(phase)
            + 0.35 * math.sin(2.0 * math.pi * MODE_HZ * t)
            + rng.gauss(0.0, NOISE_SD)
        )
    return out


def main() -> int:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    x = signal()

    # .txt, not .csv: Godot's importer treats any .csv under res:// as a TRANSLATION file and
    # generates a Translation resource beside it. This is one float per line and not a table.
    csv_path = FIXTURES / "spectrum_signal.txt"
    # %.17g round-trips a double exactly, so the two implementations are fed the same bits and a
    # disagreement is never about the fixture.
    csv_path.write_text("\n".join("%.17g" % v for v in x) + "\n")

    freqs, _starts, frames = spectrogram(np.asarray(x), SAMPLE_RATE_HZ)
    mags = frames.mean(axis=0)

    frame_len = int(round(FRAME_SECONDS * SAMPLE_RATE_HZ))
    hop = max(1, int(round(frame_len * (1.0 - OVERLAP_FRACTION))))

    payload = {
        "generated_by": "tools/spectrum_oracle.py via resonance_analysis.spectrogram",
        "sample_rate_hz": SAMPLE_RATE_HZ,
        "frame_seconds": FRAME_SECONDS,
        "overlap_fraction": OVERLAP_FRACTION,
        "frame_len": frame_len,
        "hop": hop,
        "frames": int(frames.shape[0]),
        "mode_hz": MODE_HZ,
        "bin_hz": float(freqs[1] - freqs[0]),
        "mags": [float(v) for v in mags],
    }
    (FIXTURES / "spectrum_oracle.json").write_text(json.dumps(payload, indent=1) + "\n")

    print(f"{len(x)} samples -> {payload['frames']} frames, {len(payload['mags'])} bins")
    print(f"wrote {csv_path.name} and spectrum_oracle.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
